spring:
  datasource:
    url: jdbc:mysql://localhost:3306/liv2train
    username: dev
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logger:
  level: com.example.Liv2Train